services:
  _defaults:
    autowire: true
    public: false
  ProudCommerce\OxidConsoleModuleactivator\Command\Moduleactivator:
    class: ProudCommerce\OxidConsoleModuleactivator\Command\ModuleactivatorCommand
    tags:
      - { name: 'console.command', command: 'pc:module:activator', description: 'Activates multiple modules via YAML configuration file.' }
